# Generated by Django 2.0.9 on 2019-02-08 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarea', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='creaTarea',
            new_name='Tarea',
        ),
    ]
