# Generated by Django 2.0.9 on 2019-02-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarea', '0002_auto_20190208_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
